/**
 * 
 */
package consumer_data_privacy_hba;

import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Scanner;
import java.util.SortedMap;
import java.util.TreeMap; 


/**
 * @author Zeeshan
 *
 */
public class ConsumerDataPrivacyHBA {
	
	String alice, bob;
	
	public ConsumerDataPrivacyHBA() {
		alice="";
		bob="";
	}
	
	
	public static String getSHA(String input){ 
        try { 
  
            // Static getInstance method is called with hashing SHA 
            MessageDigest md = MessageDigest.getInstance("SHA-256"); 
  
            // digest() method called 
            // to calculate message digest of an input 
            // and return array of byte 
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            // Convert byte array into sign-magnitude  representation 
            BigInteger no = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashtext = no.toString(16); 
  
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
  
            return hashtext; 
        } 
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) { 
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
  
            return null; 
        } 
    } 
	
	 
	 public void hashMatch() {
	 	
	 	System.out.println("\nHashCode Generated by SHA-256 for:"); 
        System.out.println("\n Alice \"" + alice + "\" : " + getSHA(alice)); 
  	    System.out.println("\n Bob \"" + bob + "\" : " + getSHA(bob)); 
  	    
  	    if (alice.equals(bob))
  	    	System.out.println("\n Alice and Bob Matches");
  	    else
  	    	System.out.println("\n Alice and Bob Don't Match");    	
	 }
	
	
	
	public void readFromAlice(){
    	try {
    			FileReader fr = new FileReader("input/alice.txt");
    			Scanner sc =new Scanner(fr);
    			while (sc.hasNextLine()) {
    				alice=sc.nextLine();
    			}
    			sc.close();
    	}catch(IOException e) {
    		System.out.println("Exception in reading from Alice");
    		e.printStackTrace();
    	}
		
	}
	
	

	public void readFromBob() {
		
		try {
			FileReader fr = new FileReader("input/bob.txt");
			Scanner sc =new Scanner(fr);
			while (sc.hasNextLine()) {
				bob=sc.nextLine();
			}
			sc.close();
		}catch(IOException e) {
		System.out.println("Exception in reading from Bob");
		e.printStackTrace();
	}
		
	}

	
	public void readFile(String location) {
		
		Map <String, SortedMap <String,String>> hmap = new HashMap<String, SortedMap <String,String>>();
		String line ="";
		try {
			FileReader fr = new FileReader(location);
			Scanner sc =new Scanner(fr);
			while (sc.hasNextLine()) {
				line=sc.nextLine();
				String[] row=line.split("\t");
				
				if (isHomozygous(row[3])) {
					if(hmap.containsKey(row[1])) 
						hmap.get(row[1]).put(row[0],row[3]);
					else {
						SortedMap <String,String> sm=new TreeMap<String,String>();
						sm.put(row[0],row[3]);
						hmap.put(row[1],sm);		
					}
				}
			}
			sc.close();
			
			System.out.println("\nContents of Map : " +hmap);
	}catch(IOException e) {
		System.out.println("Exception in reading at "+location);
		e.printStackTrace();
	}	
	}
	
	public boolean isHomozygous(String allele) {
		if (allele.charAt(0)==allele.charAt(1))
			return true;
		else 
			return false;
	}
	
	
}




























